# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import random
import string
import SdkOcr


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1430, 848)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(260, 90, 371, 341))
        self.label_image.setStyleSheet("border-width: 1px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-color: rgb(0, 0, 0)")
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 91, 51))
        palette = QtGui.QPalette()
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-weight:bold\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 230, 81, 17))
        self.label_3.setStyleSheet("font-weight:bold")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 90, 111, 17))
        self.label_4.setStyleSheet("font-weight:bold")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 270, 121, 121))
        self.label_5.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(116, 116, 116);\n"
"border-style: solid;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.pushButton_openImage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openImage.setGeometry(QtCore.QRect(70, 150, 97, 26))
        self.pushButton_openImage.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 85, 0);")
        self.pushButton_openImage.setObjectName("pushButton_openImage")
        self.aboutLabel = QtWidgets.QLabel(self.centralwidget)
        self.aboutLabel.setGeometry(QtCore.QRect(380, 750, 631, 61))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.aboutLabel.setFont(font)
        self.aboutLabel.setStyleSheet("color: rgb(85, 0, 0);")
        self.aboutLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.aboutLabel.setObjectName("aboutLabel")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(860, 30, 91, 51))
        palette = QtGui.QPalette()
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("font-weight:bold\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.label_txt.setGeometry(QtCore.QRect(860, 90, 521, 341))
        self.label_txt.setObjectName("label_txt")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 90, 20, 341))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(230, 90, 20, 341))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 420, 221, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(20, 80, 221, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_distinguishImage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_distinguishImage.setGeometry(QtCore.QRect(70, 310, 97, 26))
        self.pushButton_distinguishImage.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"color: rgb(0, 85, 0);")
        self.pushButton_distinguishImage.setObjectName("pushButton_distinguishImage")
        self.label_image2 = QtWidgets.QLabel(self.centralwidget)
        self.label_image2.setGeometry(QtCore.QRect(290, 500, 261, 251))
        self.label_image2.setStyleSheet("border-width: 1px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-color: rgb(0, 0, 0)")
        self.label_image2.setText("")
        self.label_image2.setObjectName("label_image2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(270, 30, 91, 51))
        palette = QtGui.QPalette()
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font-weight:bold\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_image3 = QtWidgets.QLabel(self.centralwidget)
        self.label_image3.setGeometry(QtCore.QRect(570, 500, 261, 251))
        self.label_image3.setStyleSheet("border-width: 1px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-color: rgb(0, 0, 0)")
        self.label_image3.setText("")
        self.label_image3.setObjectName("label_image3")
        self.label_image1 = QtWidgets.QLabel(self.centralwidget)
        self.label_image1.setGeometry(QtCore.QRect(10, 500, 261, 251))
        self.label_image1.setStyleSheet("border-width: 1px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-color: rgb(0, 0, 0)")
        self.label_image1.setText("")
        self.label_image1.setObjectName("label_image1")
        self.label_image4 = QtWidgets.QLabel(self.centralwidget)
        self.label_image4.setGeometry(QtCore.QRect(850, 500, 261, 251))
        self.label_image4.setStyleSheet("border-width: 1px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-color: rgb(0, 0, 0)")
        self.label_image4.setText("")
        self.label_image4.setObjectName("label_image4")
        self.label_image5 = QtWidgets.QLabel(self.centralwidget)
        self.label_image5.setGeometry(QtCore.QRect(1130, 500, 261, 251))
        self.label_image5.setStyleSheet("border-width: 1px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-color: rgb(0, 0, 0)")
        self.label_image5.setText("")
        self.label_image5.setObjectName("label_image5")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 470, 1381, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(740, 90, 20, 341))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 440, 121, 51))
        palette = QtGui.QPalette()
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font-weight:bold\n"
"")
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1430, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #self.pushButton_openImage.clicked.connect(self.openImage)
        #self.pushButton_distinguishImage.clicked.connect(self.distinguishImage)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "系统设置"))
        self.label_3.setText(_translate("MainWindow", "功能"))
        self.label_4.setText(_translate("MainWindow", "载入图片"))
        self.pushButton_openImage.setText(_translate("MainWindow", "选择文件"))
        self.aboutLabel.setText(_translate("MainWindow", "林业有害生物识别平台"))
        self.label_9.setText(_translate("MainWindow", "生物信息"))
        self.label_txt.setHtml(_translate("MainWindow",
                                          "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                          "p, li { white-space: pre-wrap; }\n"
                                          "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:600; font-style:italic;\">\n"
                                          "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:400; font-style:normal;\"></span></p></body></html>"))
        self.pushButton_distinguishImage.setText(_translate("MainWindow", "识别图片"))
        self.label_10.setText(_translate("MainWindow", "原始图片"))
        self.label_6.setText(_translate("MainWindow", "识别后的图片"))
        self.pushButton_distinguishImage.setText(_translate("MainWindow", "识别图片"))
        self.label_10.setText(_translate("MainWindow", "原始图片"))
        self.label_6.setText(_translate("MainWindow", "目标图片"))

    def openImage(self):  # 选择本地图片上传
        global imgName  # 这里为了方便别的地方引用图片路径，我们把它设置为全局变量
        imgName, imgType = QFileDialog.getOpenFileName(self.centralwidget, "打开图片", "",
                                                               "*.jpg;;*.png;;All Files(*)")  # 弹出一个文件选择框，第一个返回值imgName记录选中的文件路径+文件名，第二个返回值imgType记录文件的类型
        # 原始图片
        jpg = QtGui.QPixmap(imgName).scaled(self.label_image.width(),
                                                    self.label_image.height())  # 通过文件路径获取图片文件，并设置图片长宽为label控件的长宽
        self.label_image.setPixmap(jpg)  # 在label控件上显示选择的图片

        print("" + imgName)

    def distinguishImage(self):

        list=SdkOcr.sdkocr(imgName)
        res = list[0]
        name = res.get("name")
        score = str(float(res.get("score")) * 100)
        baike = res.get("baike_info")

        if not bool(baike):
            description = "未收录该昆虫详细信息"
        else:
            description = baike.get("description")
        print("识别结果：" + name)
        print("准确度：" + score + '%')
        print("昆虫信息：" + description)
        if name == "非动物" :
            self.label_txt.setText("当前图片中没有昆虫")
        else :
            path_circle = "../picture/p-circle.png"
            path_extend = "../picture/p-extend.png"
            path_leaf = "../picture/p-leaf.png"
            path_rect = "../picture/p-rect.png"
            path_pherical = "../picture/p-pherical.png"
            # 1
            jpg1 = QtGui.QPixmap(path_circle).scaled(self.label_image1.width(),
                                                     self.label_image1.height())  # 通过文件路径获取图片文件，并设置图片长宽为label控件的长宽
            self.label_image1.setPixmap(jpg1)  # 在label控件上显示选择的图片
            # 2
            jpg2 = QtGui.QPixmap(path_extend).scaled(self.label_image2.width(),
                                                     self.label_image2.height())  # 通过文件路径获取图片文件，并设置图片长宽为label控件的长宽
            self.label_image2.setPixmap(jpg2)  # 在label控件上显示选择的图片
            # 3
            jpg3 = QtGui.QPixmap(path_leaf).scaled(self.label_image3.width(),
                                                   self.label_image3.height())  # 通过文件路径获取图片文件，并设置图片长宽为label控件的长宽
            self.label_image3.setPixmap(jpg3)  # 在label控件上显示选择的图片
            # 4
            jpg4 = QtGui.QPixmap(path_rect).scaled(self.label_image4.width(),
                                                   self.label_image4.height())  # 通过文件路径获取图片文件，并设置图片长宽为label控件的长宽
            self.label_image4.setPixmap(jpg4)  # 在label控件上显示选择的图片
            # 5
            jpg5 = QtGui.QPixmap(path_pherical).scaled(self.label_image5.width(),
                                                       self.label_image5.height())  # 通过文件路径获取图片文件，并设置图片长宽为label控件的长宽
            self.label_image5.setPixmap(jpg5)  # 在label控件上显示选择的图片
            #self.label_txt.setWordWrap(True)

            self.label_txt.setText("<h1>识别结果：" + name + '</h1>' + "<h2>准确度：" + score + '%' + '</h2>' + "<h4>昆虫信息：" + description + "</h4>")




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formObj = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(formObj)
    formObj.show()
    sys.exit(app.exec_())